### ISSUE TITLE
BUG: Game refuses to close

### ISSUE THREAD

**Issue by Alexejhero** [VedalAI/neuro-amongus#56]
When attempting to close the game, the WebSocketThread for whatever reason does not want to exit so it gets stuck and the game freezes up and crashes.

**Comment by EBro912** [comment]
@Alexejhero and I have been scratching our heads about this for a while, we tried disabling both threads and the issue still persists, so the issue may reside somewhere else.

One theory I had is that since both threads use `async void`, the exceptions the thread relies on to close the socket never actually gets called since C# will ignore and not catch exceptions in an async void. (See [here](https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/functional/discards)). However, after converting both threads to tasks which would solve this problem, the crashing issue still persists. Therefore as stated previously there is a high chance the problem lies somewhere else, but again we currently have no idea where.
